[versions]
agp = "8.5.2"
kotlin = "2.0.21"
accompanistInsets = "0.30.1"
airbnb-lottie = "6.0.0"
billing = "7.1.1"
cardview = "1.0.0"
conscryptAndroid = "2.5.3"
constraintlayoutCompose = "1.1.0"
googleServices = "4.4.2"
gradle = "8.10.1"
grpcOkhttp = "1.62.2"
guava = "33.3.1-android"
hilt = "1.2.0"
hiltCompiler = "2.55"
kotlinxCoroutinesAndroid = "1.8.1"
ktx = "1.15.0"
appcompat = "1.7.0"
lazyColumnScrollbar = "1.5.1"
loggingInterceptor = "5.0.0-alpha.11"

material = "1.12.0"
material3 = "1.3.1"
material_compose = "1.7.6"

gson = "2.10.1"
chrisbanes-photoView = "2.0.0"
multidex = "2.0.1"
playServicesAds = "23.6.0"
prdownloader = "1.0.2"
retrofit = "2.9.0"
activity_compose = "1.10.0"
coil = "2.7.0"
lottie = "6.0.0"
navigation_compose = "2.9.6"
okhttp3 = "4.12.0"
room = "2.6.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
exoplayer = "2.19.1"
compose-ui = "1.7.6"
lifecycle-viewmodel-ktx = "2.8.7"
kotlinCompilerExtensionVersion = "1.4.2"
glide = "4.11.0"
accompanist-systemuicontroller = "0.28.0"
androidx-constraintlayout = "2.2.0"
compose-bom = "2025.01.00"
firebase-bom = "33.8.0"
kittinunf-fuel = "2.3.1"
startupRuntime = "1.2.0"
userMessagingPlatform = "3.1.0"
media3Ui = "1.5.1"
media3Exoplayer = "1.5.1"
runtime = "1.7.6"
composeshadowsplus = "1.0.4"
firebaseMessagingKtx = "24.0.2"

easycrop = "0.1.1"
zoomable = "1.6.2"

foundation = "1.7.6"
jetbrainsKotlinJvm = "2.1.0"

[libraries]
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanistInsets" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-systemuicontroller" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }



# Hilt
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt" }

# Dagger-hilt
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltCompiler" }
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltCompiler" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltCompiler" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hiltCompiler" }

androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

# Lifecycle
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-ktx" }

# Material
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-compose = { group = "androidx.compose.material", name = "material", version.ref = "material_compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }

# Compose
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-ui" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-ui" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose-ui" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
com-google-firebase-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }

billing = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing" }
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscryptAndroid" }

gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpcOkhttp" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kittinunf-fuel = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "kittinunf-fuel" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
chrisbanes-photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "chrisbanes-photoView" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "airbnb-lottie" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
prdownloader = { module = "com.github.amitshekhariitbhu:PRDownloader", version.ref = "prdownloader" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity_compose" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation_compose" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
google-firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
exoplayer-core = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exoplayer-dash = { group = "com.google.android.exoplayer", name = "exoplayer-dash", version.ref = "exoplayer" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }


user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }

androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }

# Divers
composeshadowsplus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "composeshadowsplus" }
easycrop = { module = "io.github.mr0xf00:easycrop", version.ref = "easycrop" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
lazyColumnScrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazyColumnScrollbar" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version = "2.1.0-1.0.29" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
